services:
  db:
    image: "pgvector/pgvector:pg17"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USERNAME}"

    ports:
      - "5432:5432"