
# @name createUser
POST http://localhost:8080/user/
Content-Type: application/json

{
  "email": "leonardo@email.com",
  "firstName": "Leonardo",
  "lastName": "Sander",
  "password": "SenhaSecreta1234",
  "username": "leosander12"
}

###

# @name createEvent
POST http://localhost:8080/event/
Content-Type: application/json

{
  "day": 1,
  "month": 9,
  "hour": 23,
  "minute": 50,
  "year": 2025,
  "description": "Important Meeting migrations using JavaScrypt",
  "name": "Meeting with Ronaldo",
  "userEmail": "leonardo@email.com"
}

###

# @name findUserEvents
@userEmail = leonardo@email.com

GET http://localhost:8080/event/{{userEmail}}

###

POST http://localhost:8080/ai/{{userEmail}}

